### ISSUE TITLE
Invalid App ID

### ISSUE THREAD

**Issue by logicalstep** [dmitryrogozhny/sharepoint-lab#3]
Hi Dmitry,

Such a helpful release, thank you.
I have deployed the pre-built package to SPO 365, at site collection level, but am receiving 'Invalid APP ID'. 

Is this package only designed to be deployed at Tenant Level and not Site Collection level?

![image](https://user-images.githubusercontent.com/11743687/106147856-43673200-6170-11eb-85f7-038298bc8c68.png)

Many thanks in advance.
Trevor

**Comment by dmitryrogozhny** [comment]
Hi Trevor,

Thank you for your kind feedback and apologies for not getting back to you earlier.

I've not met the behavior you're describing with this web part. The app package does not require any additional configuration for a site collection app catalog deployment.

I've rebuilt the package just in case. It's available with the same url: [./release/table-of-contents.sppkg](https://github.com/dmitryrogozhny/sharepoint-lab/blob/master/table-of-contents/release/table-of-contents.sppkg).

 I hope that'll help.

Also, here's a quick demo of how to deploy the package to the app catalog. Just to ensure we're on the same page here:
![table-of-contents-deploy-to-site-app-catalog](https://user-images.githubusercontent.com/8382522/107930595-404fac80-6f8c-11eb-9035-4bb71942c069.gif)


Thanks,
Dmitry.

**Comment by dmitryrogozhny** [comment]
There's an issue with a similar error message, described here https://github.com/pnp/sp-dev-fx-webparts/issues/568.
 Is that the behavior you're experiencing?
 
The app details page does not work for web parts deployed to the site collection app catalog. It can still be added to the site though.

**Comment by logicalstep** [comment]
> There's an issue with a similar error message, described here [pnp/sp-dev-fx-webparts#568](https://github.com/pnp/sp-dev-fx-webparts/issues/568).
> Is that the behavior you're experiencing?
> 
> The app details page does not work for web parts deployed to the site collection app catalog. It can still be added to the site though.

Thanks so much for taking the time to reply. Yes, as above is exactly the error I was seeing when clicking the ToC icon in the apps page, but as you say, the app deploys fine and after a few minutes it stared to show in my Modern Pages webparts.

Also to say, this feature is going save us so much time, as we're deploying wiki like pages, so thank you for your great work on this!

Kind Regards,
Trevor
